# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory: ~
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: "Login Form"
                check_path: "Login Form"
                csrf_token_generator: security.csrf.token_manager
            provider: our_db_provider
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/patients, roles: ROLE_ADMIN }
#        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
            ROLE_WRITER:      [ROLE_WRITE_NOTE, ROLE_ATTACH_FORM, ROLE_ATTACH_GOAL, ROLE_SUBMIT_FOR_REVIEW]
            ROLE_REVIEWER:    [ROLE_REVIEW_NOTE, ROLE_COMMENT_NOTE, ROLE_SUBMIT_NOTE_CORRECTION, ROLE_SUBMIT_NOTE]
            ROLE_SC_AUDITOR:  [ROLE_NOTES_SEARCH_LIMITED_INDIVIDUAL, ROLE_NOTES_SEARCH_LIMITED_TIME]
            ROLE_AUDITOR:     [ROLE_NOTES_ALL, ROLE_NOTES_SEARCH, ROLE_NOTES_SEARCH_LIMITED_INDIVIDUAL, ROLE_NOTES_SEARCH_LIMITED_TIME]
            ROLE_ADMIN:       [] # this has all roles by default.
framework:
    csrf_protection: ~